import logging
from pathlib import Path
from typing import List, Optional
from app.workspaces.manager import workspace_manager

logger = logging.getLogger(__name__)


class ExportService:
    def generate_amber_crd_from_pdb(self, workspace_id: str, pdb_filename: str = "structure.pdb",
                                    crd_filename: str = "structure.crd") -> bool:
        pdb_path = workspace_manager.get_file_path(workspace_id, pdb_filename)
        crd_path = workspace_manager.get_file_path(workspace_id, crd_filename)

        if not pdb_path.exists():
            logger.error(f"Cannot generate CRD, PDB not found: {pdb_path}")
            return False

        atoms: List[float] = []
        box: Optional[List[float]] = None

        try:
            with open(pdb_path, "r", encoding="utf-8") as f:
                for line in f:
                    if line.startswith(("ATOM", "HETATM")):
                        try:
                            # Čteme natvrdo pozice jako ve Fortranu pro PDB formát
                            x = float(line[30:38])
                            y = float(line[38:46])
                            z = float(line[46:54])
                            atoms.extend([x, y, z])
                        except ValueError:
                            continue
                    elif line.startswith("CRYST1"):
                        try:
                            box = [
                                float(line[6:15]), float(line[15:24]), float(line[24:33]),
                                float(line[33:40]), float(line[40:47]), float(line[47:54])
                            ]
                        except ValueError:
                            pass

            num_atoms = len(atoms) // 3

            with open(crd_path, "w", encoding="utf-8") as f:
                # 1. Titulek (Zarovnán jako ve tvém ukázkovém souboru)
                f.write("Generated by #todo\n")

                # 2. Počet atomů (I5 formát = 5 znaků zprava zarovnáno)
                f.write(f"{num_atoms:5d}\n")

                # 3. Souřadnice (6 hodnot na řádek, každá 12 znaků a 7 míst za tečkou)
                for i in range(0, len(atoms), 6):
                    chunk = atoms[i:i + 6]
                    line_str = "".join([f"{val:12.7f}" for val in chunk])
                    f.write(f"{line_str}\n")

                # 4. Parametry boxu (opět 12.7f)
                if box:
                    # Může se stát, že angles chybí (PDB má jen xyz), pak dáme default 90.0
                    while len(box) < 6:
                        box.append(90.0)
                    box_str = "".join([f"{val:12.7f}" for val in box])
                    f.write(f"{box_str}\n")

            logger.info(f"CRD file generated at {crd_path}")
            return True

        except Exception as e:
            logger.error(f"Failed generating CRD: {e}")
            return False


export_service = ExportService()